# Generated by Django 5.1.7 on 2025-03-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.IntegerField(null=True)),
                ("date_joined", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("father_name", models.CharField(blank=True, max_length=100)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("family_name", models.CharField(max_length=50)),
                (
                    "child",
                    models.ManyToManyField(
                        related_name="child_of_families", to="main.users"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.users"
                    ),
                ),
            ],
        ),
    ]
