# Generated by Django 5.1.7 on 2025-03-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_family_family_remove_family_father_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
