# Generated by Django 5.1.6 on 2025-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="child",
            field=models.ManyToManyField(
                related_name="child_of_families", to="main.user"
            ),
        ),
    ]
